name: Tests

on:
  push:
    branches:
      - main

jobs:

  Tests:

    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: "Install Node.js"
        uses: actions/setup-node@v4.0.0

      - name: "Install testing dependencies"
        run: npm install

      - name: "Run tests"
        run: |
            mkdir coverage
            npm test

      - name: "Generate a coverage report"
        if: always()
        run: npm run coverage

      - name: "Post coverage data to Coveralls"
        if: always()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          file: ./lcov.info
